# version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowmeterai-app
    working_dir: /usr/src/flowmeterai-app
    volumes:
      - .:/usr/src/flowmeterai-app    
    environment:
      - NODE_PORT=${NODE_PORT}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - ${NODE_PORT}:80
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: flowmeterai-postgres    
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - polls_pg_data:/var/lib/postgresql/data

volumes:
  polls_pg_data:
