# version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowmeterai-app
    working_dir: /usr/src/flowmeterai-app
    volumes:
      - .:/usr/src/flowmeterai-app    
    environment:
      - NODE_PORT=80
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DB_NAME=flowmeterai
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - 80:80
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: flowmeterai-postgres    
    environment:
      - POSTGRES_DB=flowmeterai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - polls_pg_data:/var/lib/postgresql/data

volumes:
  polls_pg_data:
